name: Adventure
version: '${project.version}'
main: me.will0mane.plugins.adventure.Adventure
api-version: 1.17
loadbefore: [ ProtocolLib, PlayerNPC ]
depend: [ ProtocolLib, PlayerNPC ]
softdepend: [ MongoWillo ]
authors: [ Will0mane ]
description: Adventure Plugin
commands:
  giveitem:
    description: Gives a specific AdventureItem to the player.
  clearinv:
    description: Clears the inventory.
  shblock:
    description: Spawns a hacking block
  spawnnpc:
    description: Spawns an NPC
  debug:
    description: Debugs
  stats:
    description: Stats command.
  setitemstate:
    description: Sets an AdventureItem's current state.
  statistics:
    description: Statistics management
  createpet:
    description: Creates a pet item
  pets:
    description: Pets menu
