name: Adventure
version: '${project.version}'
main: me.will0mane.plugins.adventure.Adventure
api-version: 1.17
loadbefore: [ ProtocolLib ]
depend: [ ProtocolLib ]
authors: [ Will0mane ]
description: Adventure Plugin
commands:
  giveitem:
    description: Gives a specific AdventureItem to the player.
  clearinv:
    description: Clears the inventory.
  shblock:
    description: Spawns a hacking block
